export {typeDefs as _base} from './_base'
export {typeDefs as email} from './email'
export {typeDefs as lastName} from './lastName'
export {typeDefs as restOfName} from './restOfName'
export {typeDefs as minicexAccount} from './minicexAccount'
export {typeDefs as __resolveReference} from './__resolveReference'